name = "backend"
compatibility_date = "2024-09-25"
compatibility_flags = [ "nodejs_compat" ]

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiMWQ0ODE0NzUtZDZmNi00YzMyLThmYmEtMzdjYTM4YzhhZGIyIiwidGVuYW50X2lkIjoiMjRkMGZmMjY1ZDU0ZWJlYzhkYjJiOTEzMDk4YTJiNTE2NTVhZTVlMWIxMjNjNTQ1MjRlNzZhZWYzNGUwMzYyZSIsImludGVybmFsX3NlY3JldCI6IjA2ZGRjNTE0LTA2M2QtNDc5YS05YmRkLTUzZTk4ZjUzMjY3MSJ9.SITsn8xJEc7XgKiDLow9wqT-KskPT7LoifkHxzzhsqM"
MY_SECRET_KEY = 'kunalsharma2901'

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"